version: 2.1

executors:
  x86_64:
    docker:
      - image: heathmont/nix:alpine-x86_64-2.3.15
  arm64:
    machine:
      resource_class: arm.large
      image: ubuntu-2004:202111-01

configure_parameters: &configure_parameters
  parameters:
    platform:
      type: enum
      enum: ["x86_64", "arm64"]
      default: "x86_64"

configure_builder: &configure_builder
  <<: *configure_parameters
  executor: << parameters.platform >>
  when:
    equal: ["x86_64", << parameters.platform >>]
    resource_class: large

filters: &filters
  filters:
    branches: {}

commands:
  restore_nix_cache:
    <<: *configure_parameters
    steps:
      - restore_cache:
          keys:
            - v0-nix-<< parameters.platform >>-<< pipeline.git.revision >>
            - v0-nix-<< parameters.platform >>-<< pipeline.git.base_revision >>
            - v0-nix-<< parameters.platform >>-
  save_nix_cache:
    <<: *configure_parameters
    steps:
      - save_cache:
          key: v0-nix-<< parameters.platform >>-<< pipeline.git.revision >>
          paths:
            - /nix
      - save_cache:
          key: v0-nix-
          paths:
            - /nix

jobs:
  release:
    <<: *configure_builder
    steps:
    - checkout
    - restore_nix_cache:
        platform: << parameters.platform >>
    - run:
        name: Create << parameters.platform >> release
        command: ./nix/release.sh
        no_output_timeout: 60m
    - save_nix_cache:
        platform: << parameters.platform >>

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          <<: *filters
          cron: "0 5 * * *"  # 05:00 UTC
    jobs:
      - release:
          <<: *filters
          context: global
          platform: "x86_64"
      - release:
          <<: *filters
          context: global
          platform: "arm64"
  push:
    jobs:
      - release:
          <<: *filters
          context: global
          platform: "x86_64"
      - release:
          <<: *filters
          context: global
          platform: "arm64"
