version: 2.1

executors:
  x86_64:
    docker:
      - image: heathmont/nix:alpine-x86_64-2.3.15
    resource_class: large
  arm64:
    machine:
      resource_class: arm.large
      image: ubuntu-2004:202111-01

configure: &configure
  parameters:
    platform:
      type: enum
      enum: ["x86_64", "arm64"]
      default: "x86_64"

filters: &filters
  filters:
    branches: {}

commands:
  restore_nix_cache:
    <<: *configure
    steps:
      - restore_cache:
          keys:
            - v3-nix-<< parameters.platform >>-<< pipeline.git.revision >>
            - v3-nix-<< parameters.platform >>-<< pipeline.git.base_revision >>
            - v3-nix-<< parameters.platform >>-
  save_nix_cache:
    <<: *configure
    steps:
      - save_cache:
          key: v3-nix-<< parameters.platform >>-<< pipeline.git.revision >>
          paths:
            - /nix
            - ~/project/nix_ci_cache
      - save_cache:
          key: v3-nix-<< parameters.platform >>-
          paths:
            - /nix
            - ~/project/nix_ci_cache

jobs:
  release:
    <<: *configure
    executor: << parameters.platform >>
    steps:
    - checkout
    - restore_nix_cache:
        platform: << parameters.platform >>
    - when:
        condition:
          equal: [ "arm64", << parameters.platform >> ]
        steps:
          - run:
              name: Create << parameters.platform >> release
              command: ./nix/shell.sh "--run ./nix/release.sh"
              no_output_timeout: 60m
          - run:
              name: Save << parameters.platform >> nix_ci_cache
              command: |
                docker run -it --rm \
                  -v "$(pwd):/app" \
                  -v "nix:/nix" \
                  -v "nix-19.09-root:/root" \
                  -w "/app" "heathmont/nix:alpine-arm64-2.3.15" sh -c "
                  echo 'http2 = false' >> /etc/nix/nix.conf &&
                  echo 'sandbox = false' >> /etc/nix/nix.conf &&
                  echo 'filter-syscalls = false' >> /etc/nix/nix.conf &&
                  nix copy --no-check-sigs --to file:///app/nix_ci_cache --all
                  "
              no_output_timeout: 60m
    - when:
        condition:
          equal: [ "x86_64", << parameters.platform >> ]
        steps:
          - run:
              name: Create << parameters.platform >> release
              command: ./nix/release.sh
              no_output_timeout: 60m
    - save_nix_cache:
        platform: << parameters.platform >>

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          <<: *filters
          cron: "0 5 * * *"  # 05:00 UTC
    jobs:
      - release:
          <<: *filters
          context: global
          platform: "x86_64"
      - release:
          <<: *filters
          context: global
          platform: "arm64"
  push:
    jobs:
      - release:
          <<: *filters
          context: global
          platform: "x86_64"
      - release:
          <<: *filters
          context: global
          platform: "arm64"
