version: 2.1

commands:
  setup:
    steps:
      # - run:
      #     name: Alpine deps
      #     command: |
      #       apk --update add bash git openssh-client
      - run:
          name: Setup robot SSH key
          command: |
            mkdir -p -m 700 $HOME/.ssh
            echo "$ROBOT_SSH_KEY" | base64 -d > $HOME/.ssh/id_rsa.robot && chmod 600 $HOME/.ssh/id_rsa.robot && ssh-add $HOME/.ssh/id_rsa.robot
            echo -e "Host *\n IdentityFile $HOME/.ssh/id_rsa.robot\n IdentitiesOnly yes" > $HOME/.ssh/config
      - run:
          name: Github to known hosts
          command: |
            ssh-keyscan github.com >> $HOME/.ssh/known_hosts

  checkout_git_submodules:
    steps:
      - run:
          name: Checkout git submodules
          command: git submodule update --init --recursive
  build:
    steps:
      - run:
          name: Build
          # command: RUSTFLAGS="-C target-feature=-crt-static" cargo build --release
          command: cargo build --release

jobs:
  build:
    docker:
    # - image: rust:1.43.1-alpine3.11
    - image: rust:1
    steps:
    - checkout
    - setup
    - checkout_git_submodules
    - build


workflows:
  version: 2
  build:
    jobs:
      - build:
          context: global
