version: 2.1

executors:
  x86_64:
    docker:
      - image: heathmont/nix:alpine-x86_64-2.3.15
    resource_class: large
  arm64:
    machine:
      resource_class: arm.large
      image: ubuntu-2004:202111-01

configure: &configure
  parameters:
    platform:
      type: enum
      enum: ["x86_64", "arm64"]
      default: "x86_64"

filters: &filters
  filters:
    branches: {}

commands:
  restore_nix_cache:
    <<: *configure
    steps:
      - restore_cache:
          keys:
            - v0-nix-<< parameters.platform >>-<< pipeline.git.revision >>
            - v0-nix-<< parameters.platform >>-<< pipeline.git.base_revision >>
            - v0-nix-<< parameters.platform >>-
  save_nix_cache:
    <<: *configure
    steps:
      - save_cache:
          key: v0-nix-<< parameters.platform >>-<< pipeline.git.revision >>
          paths:
            - /nix
      - save_cache:
          key: v0-nix-<< parameters.platform >>-
          paths:
            - /nix

jobs:
  release:
    <<: *configure
    executor: << parameters.platform >>
    steps:
    - checkout
    - restore_nix_cache:
        platform: << parameters.platform >>
    - when:
        condition:
          equal: [ "arm64", << parameters.platform >> ]
        steps:
          - run:
              name: Restore << parameters.platform >> nix volume
              command: |
                ./nix/shell.sh "--run 'echo \"==> creating docker volume\"'" && \
                sudo mkdir -p /nix && \
                sudo rsync -a /nix/ /var/lib/docker/volumes/nix/_data/ && \
                sudo chown -R root /var/lib/docker/volumes/nix/_data
              no_output_timeout: 60m
          - run:
              name: Create << parameters.platform >> release
              command: ./nix/shell.sh "--run ./nix/release.sh"
              no_output_timeout: 60m
          - run:
              name: Save << parameters.platform >> nix volume
              command: |
                sudo mv /var/lib/docker/volumes/nix/_data /nix && \
                sudo chown -R circleci /nix
              no_output_timeout: 60m
    - when:
        condition:
          equal: [ "x86_64", << parameters.platform >> ]
        steps:
          - run:
              name: Create << parameters.platform >> release
              command: ./nix/release.sh
              no_output_timeout: 60m
    - save_nix_cache:
        platform: << parameters.platform >>

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          <<: *filters
          cron: "0 5 * * *"  # 05:00 UTC
    jobs:
      - release:
          <<: *filters
          context: global
          platform: "x86_64"
      - release:
          <<: *filters
          context: global
          platform: "arm64"
  push:
    jobs:
      - release:
          <<: *filters
          context: global
          platform: "x86_64"
      - release:
          <<: *filters
          context: global
          platform: "arm64"
